param(
    [switch]$TorrentRqbit
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$releaseScript = Join-Path $PSScriptRoot "build-release.ps1"
$installerDir = Join-Path $repoRoot "dist\installer"
$setupDir = Join-Path $repoRoot "setup"
$installerOutputDir = Join-Path $env:TEMP "NebulaDM-installer-output"
$issPath = Join-Path $installerDir "NebulaDM.iss"
$targetDirName = if ($TorrentRqbit) { "target-release-rqbit-desktop" } else { "target-release-desktop" }
$releaseBinary = Join-Path $repoRoot "$targetDirName\release\desktop.exe"
$extensionSource = Join-Path $repoRoot "extensions\browser"
$ffmpegBundleSource = Join-Path $repoRoot "tools\ffmpeg\ffmpeg.exe"
$ytDlpBundleSource = Join-Path $repoRoot "tools\yt-dlp\yt-dlp.exe"
$installerIcon = Join-Path $repoRoot "assets\nebuladm-logo.ico"
$wizardImage = Join-Path $repoRoot "assets\installer-wizard.bmp"
$wizardSmallImage = Join-Path $repoRoot "assets\installer-wizard-small.bmp"
$outputBaseFilename = "NebulaDM-Setup-" + (Get-Date -Format "yyyyMMdd-HHmmss")
$canonicalInstallerPath = Join-Path $setupDir "NebulaDM-Setup.exe"
$installerPattern = "NebulaDM-Setup-*.exe"

Write-Host "Preparing NebulaDM release payload..."
if ($TorrentRqbit) {
    & $releaseScript -TorrentRqbit
}
else {
    & $releaseScript
}

New-Item -ItemType Directory -Path $installerDir -Force | Out-Null
New-Item -ItemType Directory -Path $installerOutputDir -Force | Out-Null
New-Item -ItemType Directory -Path $setupDir -Force | Out-Null

Get-ChildItem -Path $installerOutputDir -Filter $installerPattern -File -Force -ErrorAction SilentlyContinue |
    ForEach-Object {
        Remove-Item -LiteralPath $_.FullName -Force
    }

if (Test-Path $canonicalInstallerPath) {
    Remove-Item -LiteralPath $canonicalInstallerPath -Force
}

$appVersion = (Get-Content (Join-Path $repoRoot "apps\desktop\Cargo.toml") | Where-Object { $_ -match '^version = ' } | Select-Object -First 1)
$appVersion = ($appVersion -replace 'version = "', '') -replace '"', ''

$issContent = @"
; Generated by NebulaDM
[Setup]
AppName=NebulaDM
AppPublisher=NebulaDM
AppVersion=$appVersion
DefaultDirName={autopf}\NebulaDM
DefaultGroupName=NebulaDM
OutputDir=$installerOutputDir
OutputBaseFilename=$outputBaseFilename
Compression=lzma
SolidCompression=yes
WizardStyle=modern
UninstallDisplayIcon={app}\NebulaDM.exe
SetupIconFile=$installerIcon
WizardImageFile=$wizardImage
WizardSmallImageFile=$wizardSmallImage
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest

[Files]
Source: "$releaseBinary"; DestDir: "{app}"; DestName: "NebulaDM.exe"; Flags: ignoreversion
Source: "$extensionSource\*"; DestDir: "{app}\browser-extension"; Flags: ignoreversion recursesubdirs createallsubdirs

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional shortcuts:"
Name: "startupbackground"; Description: "Launch NebulaDM at sign in in background mode"; GroupDescription: "Background behavior:"

[Icons]
Name: "{group}\NebulaDM"; Filename: "{app}\NebulaDM.exe"
Name: "{group}\Uninstall NebulaDM"; Filename: "{uninstallexe}"
Name: "{autodesktop}\NebulaDM"; Filename: "{app}\NebulaDM.exe"; Tasks: desktopicon

[Registry]
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "NebulaDM"; ValueData: """{app}\NebulaDM.exe"" --background"; Tasks: startupbackground; Flags: uninsdeletevalue

[Run]
Filename: "{app}\NebulaDM.exe"; Description: "Launch NebulaDM"; Flags: nowait postinstall skipifsilent
Filename: "{app}\browser-extension"; Description: "Open browser extension folder"; Flags: shellexec postinstall unchecked skipifsilent
"@

if (Test-Path $ffmpegBundleSource) {
    $issContent = $issContent -replace '(?ms)\[Files\]\r?\n', "[Files]`r`nSource: `"$ffmpegBundleSource`"; DestDir: `"{app}\tools`"; DestName: `"ffmpeg.exe`"; Flags: ignoreversion`r`n"
}
if (Test-Path $ytDlpBundleSource) {
    $issContent = $issContent -replace '(?ms)\[Files\]\r?\n', "[Files]`r`nSource: `"$ytDlpBundleSource`"; DestDir: `"{app}\tools`"; DestName: `"yt-dlp.exe`"; Flags: ignoreversion`r`n"
}

Set-Content -LiteralPath $issPath -Value $issContent

$iscc = Get-Command "iscc" -ErrorAction SilentlyContinue
if (-not $iscc) {
    $commonIscc = @(
        (Join-Path $env:LOCALAPPDATA "Programs\Inno Setup 6\ISCC.exe"),
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        "C:\Program Files\Inno Setup 6\ISCC.exe"
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1

    if ($commonIscc) {
        $iscc = @{ Source = $commonIscc }
    }
    else {
        Write-Host "Inno Setup compiler (iscc) was not found on PATH."
        Write-Host "Script generated at: $issPath"
        Write-Host "Install Inno Setup and run: iscc `"$issPath`""
        exit 0
    }
}

Write-Host "Building NebulaDM installer with Inno Setup..."
& $iscc.Source $issPath

$builtInstallerPath = Join-Path $installerOutputDir ($outputBaseFilename + ".exe")
if (-not (Test-Path $builtInstallerPath)) {
    throw "Expected installer output was not found at $builtInstallerPath"
}

# Keep Inno's output in temp for reliable compilation, then publish a stable
# setup asset path that is easy to attach to GitHub Releases.
Copy-Item -LiteralPath $builtInstallerPath -Destination $canonicalInstallerPath -Force

Write-Host ""
Write-Host "Installer build complete."
Write-Host "GitHub Release asset: $canonicalInstallerPath"
Write-Host "Build copy: $builtInstallerPath"
